using System.Collections.Generic;
using System.Linq;
using System.Text;
using Microsoft.CodeAnalysis;

namespace MZikmund.Toolkit.SourceGenerators;

/// <summary>
/// Emits a <c>GeneratedPackageInfo</c> static class into the consuming assembly with a
/// list of NuGet-style package references derived from the compilation's referenced
/// assemblies. Intended to back "About" / "Third-party software" UI without requiring
/// the consumer to maintain a hand-rolled list.
/// </summary>
/// <remarks>
/// Filters out framework / SDK / source-generator assemblies so the resulting list
/// reflects roughly the user-facing dependencies. Uses the assembly name + version
/// rather than the original PackageReference id; for most app dependencies these
/// agree, and where they don't the consumer can swap in their own list.
/// </remarks>
[Generator(LanguageNames.CSharp)]
public sealed class PackageInfoGenerator : IIncrementalGenerator
{
    private const string TargetNamespace = "MZikmund.Toolkit.Generated";
    private const string TargetClassName = "GeneratedPackageInfo";

    /// <inheritdoc />
    public void Initialize(IncrementalGeneratorInitializationContext context)
    {
        var packagesProvider = context.CompilationProvider
            .Select(static (compilation, _) =>
            {
                var packages = new List<(string Id, string Version)>();
                foreach (var reference in compilation.ReferencedAssemblyNames)
                {
                    if (PackageInfoFilter.IsUserFacing(reference.Name))
                    {
                        packages.Add((reference.Name, reference.Version.ToString()));
                    }
                }

                packages.Sort(static (a, b) => string.CompareOrdinal(a.Id, b.Id));
                return (IReadOnlyList<(string Id, string Version)>)packages;
            });

        context.RegisterSourceOutput(packagesProvider, (productionContext, packages) =>
        {
            productionContext.AddSource($"{TargetClassName}.g.cs", BuildSource(packages));
        });
    }

    private static string BuildSource(IReadOnlyList<(string Id, string Version)> packages)
    {
        var builder = new StringBuilder();
        builder.AppendLine("// <auto-generated />");
        builder.AppendLine("#nullable enable");
        builder.AppendLine();
        builder.AppendLine($"namespace {TargetNamespace};");
        builder.AppendLine();
        builder.AppendLine("/// <summary>");
        builder.AppendLine("/// Auto-generated list of user-facing package references in the consuming assembly.");
        builder.AppendLine("/// Intended for About / Third-party software pages.");
        builder.AppendLine("/// </summary>");
        builder.AppendLine($"internal static class {TargetClassName}");
        builder.AppendLine("{");
        builder.AppendLine("    /// <summary>A single package entry: id and version.</summary>");
        builder.AppendLine("    public sealed record PackageInfo(string Id, string Version);");
        builder.AppendLine();
        builder.AppendLine("    /// <summary>Returns the user-facing package references baked in at compile time.</summary>");
        builder.AppendLine("    public static global::System.Collections.Generic.IReadOnlyList<PackageInfo> GetPackages() => Packages;");
        builder.AppendLine();
        builder.AppendLine("    private static readonly PackageInfo[] Packages = new PackageInfo[]");
        builder.AppendLine("    {");
        foreach (var (id, version) in packages)
        {
            builder.Append("        new PackageInfo(\"")
                .Append(id)
                .Append("\", \"")
                .Append(version)
                .AppendLine("\"),");
        }
        builder.AppendLine("    };");
        builder.AppendLine("}");

        return builder.ToString();
    }
}
