# This workflow will build a .NET project
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-net

name: .NET

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Setup .NET
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: 8.0.x
        cache: true
    - name: Install GitVersion
      run: dotnet tool install --global GitVersion.Tool
    - name: Add .NET tools to PATH
      run: echo "::add-path::$(echo $HOME/.dotnet/tools)"
    - name: Generate Version
      id: gitversion
      run: gitversion /output json /showvariable FullSemVer
    - name: Restore workloads
      run: dotnet workload restore src/MZikmund.Toolkit.sln
    - name: Restore dependencies
      run: dotnet restore src/MZikmund.Toolkit.sln --locked-mode
    - name: Build
      run: dotnet build --no-restore src/MZikmund.Toolkit.sln /p:PackageVersion=${{ steps.gitversion.outputs.FullSemVer }}
    # - name: Test
    #   run: dotnet test --no-build --verbosity normal
    # - name: Pack
    #   run: dotnet pack src/MZikmund.Toolkit.sln
    - name: Publish artifacts
      uses: actions/upload-artifact@v4
      with:
        name: nuget-packages
        path: src/**/*.nupkg,src/**/*.snupkg
